---
title: "Research Group Members"
---
::: {#center}
## <strong>Faculty Members</strong>

- 张敬林　山东大学教授、博士生导师
- 鲁威志　山东大学副教授、硕士生导师
- 李垣江　江苏科技大学教授、硕士生导师

## <strong>Ph.D. Students (On-going) @ Shandong University</strong>

- 陈庆辉　2024级博士在读
- 张泽恺　2024级博士在读
- 刘云龙　2025级博士在读
- 周　涛　2025级博士在读
- 耿云达　2026级直博在读
- 孙　奇　2026级博士在读

## <strong>M.Sc. Students (On-going) @ Shandong University</strong>

- 王志强　2024级硕士在读
- 侯晓光　2024级硕士在读
- 张群书　2024级硕士在读
- 孙明龙　2025级硕士在读
- 边昌林　2025级硕士在读

## <strong>M.Sc. Students (On-going) @ Qilu University of Technology</strong>

- 荆帅楠　2024级硕士在读
- 王　贺　2024级硕士在读
- 刘子龙　2025级硕士在读
- 高　宇　2025级硕士在读

## <strong>M.Sc. Students (On-going) @ Linyi University</strong>

- 邢雪梅　2024级硕士在读
- 沈震环　2025级硕士在读
- 任鑫阳　2025级硕士在读


## <strong>Graduated students</strong>
- **姓名**：丁世娇　2022届硕士（山东大学）  
  **去向**：就职于**浪潮集团有限公司**

- **姓名**：熊毛毛　2023届硕士（山东大学）  
  **去向**：就职于**华为**

- **姓名**：王家树　2023届硕士（临沂大学）  
  **去向**：深造于**同济大学**

- **姓名**： 胡唱唱　2023届硕士（临沂大学）  
  **去向**：深造于**移动**

- **姓名**：郭　雯　2022级本科自动化（卓越班）  
  **去向**：深造于**上海交通大学自动化与感知学院**  

- **姓名**：张　凯　2022级本科机器人工程  
  **去向**：深造于**香港大学**    

- **姓名**：王泽瑜　2022级本科机器人工程   
  **去向**：深造于**北京理工大学自动化学院**  

- **姓名**：耿云达　2022级本科机器人工程   
  **去向**：深造于**山东大学控制学院直博**  

- **姓名**：蔡景豪　2022级本科自动化（卓越班）  
  **去向**：深造于**中国科学技术大学**  

- **姓名**：罗子杰　2022级本科自动化（卓越班）  
  **去向**：深造于**北京航空航天大学自动化科学与电气工程学院**  

- **姓名**：李翰乾　2021级本科自动化（卓越班）  
  **去向**：深造于**香港科技大学**  
::: 